version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: frontend-prod
    ports:
      - "3000:80"

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11.6}
      target: dev
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces/vespadb/

  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: app
    tty: true
    ports:
      - "8001:8000"
    volumes:
      - .:/workspaces/vespadb/
    command: [ "serve", "--dev" ]
    working_dir: /workspaces/vespadb/
    environment:
      - PYTHONPATH=/workspaces/vespadb
      - debug=True
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:latest
    platform: linux/amd64
    environment:
      POSTGRES_DB: vespadb
      POSTGRES_USER: vespauser
      POSTGRES_PASSWORD: vespauserpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vespauser -d vespadb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery-worker
    volumes:
      - .:/workspaces/vespadb/
    environment:
      - TZ=UTC
    depends_on:
      db:
        condition: service_healthy

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery-beat
    volumes:
      - .:/workspaces/vespadb/
    environment:
      - TZ=UTC
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:


networks:
  default:
    name: vespadb-network
